name: Run Mpanisa Bot

on:
  schedule:
    - cron: '45 14 * * 5'
    - cron: '15 7 * * 0'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 110
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install -r requirements.txt
      - run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROUP_ID: ${{ secrets.GROUP_ID }} 
